name: Generate ER Diagrams
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install mermaid-cli
      run: npm install -g @mermaid-js/mermaid-cli
    - name: Generate ER Diagram
      run: mmdc -i diagram.mermaid -o diagram.png
    - name: Commit and Push Diagram
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add diagram.png
        git commit -m 'Auto-generate ER diagram'
        git push